exports.formatMonth = function (month) {
	if (!isNaN(+month)) return month.toString().padStart(2, "0")
	else {
		const map = {
			jan: 1,
			janv: 1,
			janvier: 1,
			january: 1,
			fev: 2,
			feb: 2,
			fevrier: 2,
			février: 2,
			february: 2,
			mar: 3,
			mars: 3,
			march: 3,
			avr: 4,
			apr: 4,
			avril: 4,
			"d'avril": 4,
			april: 4,
			mai: 5,
			may: 5,
			jun: 6,
			juin: 6,
			june: 6,
			jul: 7,
			juillet: 7,
			july: 7,
			aug: 8,
			aout: 8,
			août: 8,
			"d'août": 8,
			august: 8,
			sep: 9,
			sept: 9,
			septembre: 9,
			september: 9,
			oct: 10,
			octobre: 10,
			october: 10,
			nov: 11,
			novembre: 11,
			november: 11,
			dec: 12,
			decembre: 12,
			décembre: 12,
			december: 12,
		}
		return exports.formatMonth(map[month.toLowerCase()])
	}
}
